name: PR-checks
on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v4

      - name: Install npm Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Tests
        run: npm run test

      - name: Build
        run: npm run build
